### ISSUE TITLE
Error 404: Deployment Not Found

### ISSUE THREAD

**Issue by ryanbarillosofficial** [Pmacdon15/pats-pretrip#21]
Don't know what's wrong.
But something to check on your end.

![Screenshot 2024-08-26 015909](https://github.com/user-attachments/assets/c9273bef-b67d-4398-a88e-2aa355726f70)

**Comment by Pmacdon15** [comment]
Where did you find the link you are using? If you go to the git hub and go to deployments the link works fine.
``` html

https://pats-pretrip-2l03suatn-pmacdon15s-projects.vercel.app
```
Or 

``` Html
https://patspretrips.vercel.app
```

**Comment by Pmacdon15** [comment]
Just updated the url in the README as well.

**Comment by Pmacdon15** [comment]
Updated on the repo link as well.
